apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list-db
  template:
    metadata:
      labels:
        app: todo-list-db
    spec:
      containers:
        - name: todo-list-db
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: todo
            - name: MYSQL_DATABASE
              value: todo
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: todo-list-db
spec:
  selector:
    app: todo-list-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
