services:
  api:
    image: 'node:18'
    working_dir: '/todo-list-api'
    volumes:
      - './:/todo-list-api'
    ports:
      - 3001:3000
    command: >
      bash -c "npm i && npm run start:dev"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: todo

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
